{"name": "test_add_member_fail[user3-1111-请填写合法的手机号]", "status": "passed", "attachments": [{"name": "log", "source": "f2aadcc2-61bb-4d27-b3b8-97ccc583e42e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user3'"}, {"name": "phone", "value": "'1111'"}, {"name": "expect", "value": "'请填写合法的手机号'"}], "start": 1626597508749, "stop": 1626597520305, "uuid": "0c0161d7-3473-4d47-8367-e1ec2a1884ed", "historyId": "234428484d32023bba9f8116ebd2db9d", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "9848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}