{"name": "test_add_member_fail[-11528872804-姓名不能为空1]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '姓名不能为空1'\n     but: was '姓名不能为空'", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x000002E728299630>\nuser = '', phone = '11528872804', expect = '姓名不能为空1'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '姓名不能为空1'\nE            but: was '姓名不能为空'\n\ntestcases\\test_addMember.py:29: AssertionError"}, "attachments": [{"name": "log", "source": "24fff77f-320c-40b6-93c2-68a7d68635f2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "''"}, {"name": "phone", "value": "'11528872804'"}, {"name": "expect", "value": "'姓名不能为空1'"}], "start": 1626598091892, "stop": 1626598103318, "uuid": "fd4778a4-2091-4283-a908-865ca7869133", "historyId": "fd2d3b54b1512f5e248e96f7d769f23d", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "11180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}